import { Template } from 'e2b'

export const template = Template()
  .fromImage('node:21-slim')
  .setUser('root')
  .setWorkdir('/')
  .runCmd('apt-get update && apt-get install -y curl && apt-get clean && rm -rf /var/lib/apt/lists/*')
  .copy('compile_page.sh', '/compile_page.sh')
  .runCmd('chmod +x /compile_page.sh')
  .setUser('user')
  .setWorkdir('/home/user')
  .runCmd('npx --yes create-next-app@15.3.3 nextjs-app --yes')
  .runCmd('cd nextjs-app && npx --yes shadcn@2.6.3 init --yes -b neutral --force')
  .runCmd('cd nextjs-app && npx --yes shadcn@2.6.3 add --all --yes')
  .runCmd('mv /home/user/nextjs-app/* /home/user/nextjs-app/.[!.]* /home/user/ 2>/dev/null || true')
  .runCmd('rm -rf /home/user/nextjs-app')
  .setWorkdir('/home/user')
  .setStartCmd('/compile_page.sh', 'sleep 20')